version: "3.1"
services:  
  # angular
  angular:
    init: true
    container_name: quiniela-ui
    build:
      context: .
      dockerfile: quiniela-ui/Dockerfile
    ports:
      - 4200:4200
    
  # iris
  iris:
    init: true
    container_name: iris
    build:
      context: .
      dockerfile: iris/Dockerfile
    ports:
      - 52774:52773
    volumes:
    - ./shared:/shared
    environment:
    - ISC_DATA_DIRECTORY=/shared/durable
    command: --check-caps false